/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminClientesRouteImport } from './routes/admin.clientes'
import { Route as AdminFinanceiroRouteImport } from './routes/admin.financeiro'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminProjetosRouteImport } from './routes/admin.projetos'
import { Route as AdminAuthCoresTextosRouteImport } from './routes/admin._auth/cores-textos'
import { Route as AdminAuthDashboardRouteImport } from './routes/admin._auth/dashboard'
import { Route as AdminAuthLogoNavbarRouteImport } from './routes/admin._auth/logo-navbar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/admin/clientes',
  path: '/admin/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFinanceiroRoute = AdminFinanceiroRouteImport.update({
  id: '/admin/financeiro',
  path: '/admin/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjetosRoute = AdminProjetosRouteImport.update({
  id: '/admin/projetos',
  path: '/admin/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthCoresTextosRoute = AdminAuthCoresTextosRouteImport.update({
  id: '/admin/_auth/cores-textos',
  path: '/admin/cores-textos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthDashboardRoute = AdminAuthDashboardRouteImport.update({
  id: '/admin/_auth/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthLogoNavbarRoute = AdminAuthLogoNavbarRouteImport.update({
  id: '/admin/_auth/logo-navbar',
  path: '/admin/logo-navbar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/projetos': typeof AdminProjetosRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/cores-textos': typeof AdminAuthCoresTextosRoute
  '/admin/dashboard': typeof AdminAuthDashboardRoute
  '/admin/logo-navbar': typeof AdminAuthLogoNavbarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/projetos': typeof AdminProjetosRoute
  '/admin': typeof AdminIndexRoute
  '/admin/cores-textos': typeof AdminAuthCoresTextosRoute
  '/admin/dashboard': typeof AdminAuthDashboardRoute
  '/admin/logo-navbar': typeof AdminAuthLogoNavbarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/projetos': typeof AdminProjetosRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/_auth/cores-textos': typeof AdminAuthCoresTextosRoute
  '/admin/_auth/dashboard': typeof AdminAuthDashboardRoute
  '/admin/_auth/logo-navbar': typeof AdminAuthLogoNavbarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/clientes'
    | '/admin/financeiro'
    | '/admin/login'
    | '/admin/projetos'
    | '/admin/'
    | '/admin/cores-textos'
    | '/admin/dashboard'
    | '/admin/logo-navbar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/clientes'
    | '/admin/financeiro'
    | '/admin/login'
    | '/admin/projetos'
    | '/admin'
    | '/admin/cores-textos'
    | '/admin/dashboard'
    | '/admin/logo-navbar'
  id:
    | '__root__'
    | '/'
    | '/admin/clientes'
    | '/admin/financeiro'
    | '/admin/login'
    | '/admin/projetos'
    | '/admin/'
    | '/admin/_auth/cores-textos'
    | '/admin/_auth/dashboard'
    | '/admin/_auth/logo-navbar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminClientesRoute: typeof AdminClientesRoute
  AdminFinanceiroRoute: typeof AdminFinanceiroRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminProjetosRoute: typeof AdminProjetosRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAuthCoresTextosRoute: typeof AdminAuthCoresTextosRoute
  AdminAuthDashboardRoute: typeof AdminAuthDashboardRoute
  AdminAuthLogoNavbarRoute: typeof AdminAuthLogoNavbarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/admin/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/financeiro': {
      id: '/admin/financeiro'
      path: '/admin/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AdminFinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projetos': {
      id: '/admin/projetos'
      path: '/admin/projetos'
      fullPath: '/admin/projetos'
      preLoaderRoute: typeof AdminProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_auth/cores-textos': {
      id: '/admin/_auth/cores-textos'
      path: '/admin/cores-textos'
      fullPath: '/admin/cores-textos'
      preLoaderRoute: typeof AdminAuthCoresTextosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_auth/dashboard': {
      id: '/admin/_auth/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAuthDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_auth/logo-navbar': {
      id: '/admin/_auth/logo-navbar'
      path: '/admin/logo-navbar'
      fullPath: '/admin/logo-navbar'
      preLoaderRoute: typeof AdminAuthLogoNavbarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminClientesRoute: AdminClientesRoute,
  AdminFinanceiroRoute: AdminFinanceiroRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminProjetosRoute: AdminProjetosRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAuthCoresTextosRoute: AdminAuthCoresTextosRoute,
  AdminAuthDashboardRoute: AdminAuthDashboardRoute,
  AdminAuthLogoNavbarRoute: AdminAuthLogoNavbarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
